worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 ipv6=off valid=30s;
    include       /etc/nginx/mime.types;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_max_body_size 10M;

    upstream security {
        server security:3000;
    }
    upstream uploader {
        server uploader:3000;
    }
    upstream minio {
        server storage:9000;
    }

    server {
        listen 80;
        server_name localhost;

        location = /internal-auth {
            internal;
            proxy_pass http://security/v1/token/validation;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
        }

        # === Анонимные маршруты ===

        location = /v1/register {
            limit_except POST { deny all; }
            proxy_pass http://security/v1/token;
        }

        location = /v1/token {
            limit_except POST { deny all; }
            proxy_pass http://security/v1/token;
        }

        # === Защищённые маршруты ===

        location = /v1/user {
            limit_except GET { deny all; }
            auth_request /internal-auth;
            proxy_pass http://security/v1/user;
        }

        location = /v1/upload {
            limit_except POST { deny all; }
            auth_request /internal-auth;
            proxy_pass http://uploader/v1/upload;
        }

        location ~ ^/images/(?<filename>.+)$ {
            limit_except GET { deny all; }
            auth_request /internal-auth;
            proxy_set_header Host $http_host;
            proxy_pass http://minio/images/$filename$is_args$args;
        }
    }
}